### ISSUE TITLE
Overload CPU with json messages on 1.19

### ISSUE THREAD

**Issue by Kapitowa** [Brikster/Chatty#180]
Server start lagging with every message, which sends with json enabled feature (lag can be found in ProtocolLib and with more players 100+ online): https://spark.lucko.me/neEWEyR4hx
Software: Paper 1.19 and latest Chatty
On 1.18 problem doesn't exists.

**Comment by Brikster** [comment]
I don't see problem with Chatty in your spark report.
There's ProtocolLib laggy method that checks packet's plugin-caller. Maybe it badly works with custom packets sent by Chatty.

It will be fixed in Chatty rewrite (v3), that will use adventure lib instead of fancymessage with legacy crutches. But it's not ready for now, and I don't know when I'll have enough time to release it.
